### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by DonaldTsang** [cloudinary/fuif#5]
Just wondering if it will have Golang support to make the FUIF standard more common place.

**Comment by idobarnoam** [comment]
@DonaldTsang Let me take this internally with the team.

We'll update here with any insights.

**Comment by brunoais** [comment]
@idobarnoam Any insights?

**Comment by jonsneyers** [comment]
FUIF development has stopped since FUIF is subsumed in JPEG XL (https://jpeg.org/jpegxl/index.html), which is based on a combination of Pik and FUIF.

Once the JPEG XL standard is ready, we are planning to make a royalty-free and open source reference implementation available.

This reference implementation will contain a C library, and I expect there will be bindings for various programming languages.

**Comment by DonaldTsang** [comment]
@jonsneyers thanks for the explanation
